#!/bin/bash 
./configure-basic

# configuring 
modprobe kvm_intel

# Configure packet forwarding
sysctl -w net.ipv4.conf.all.forwarding=1

# Avoid "nf_conntrack: table full, dropping packet"
sysctl -w net.ipv4.netfilter.ip_conntrack_max=99999999

# Avoid "neighbour: arp_cache: neighbor table overflow!"
sysctl -w net.ipv4.neigh.default.gc_thresh1=1024
sysctl -w net.ipv4.neigh.default.gc_thresh2=2048
sysctl -w net.ipv4.neigh.default.gc_thresh3=4096


# Add CAP_NET_ADMIN to firecracker (for TUNSETIFF ioctl)
setcap cap_net_admin=eip firecracker

# to set up network for the VM we need a tap device. For docker we will need the following.